name: Best-Movies | Next.js 13 CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository
       uses: actions/checkout@v2
       
     - name: Install Vercel CLI
       run: npm install --global vercel@latest
       
