name: Best-Movies | Next.js 13 CI/CD

env:
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN }}
  VAR_VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo values"
        run: |
          echo ${{env.VERCEL_TOKEN}}
          echo ${{env.VAR_VERCEL_TOKEN}}
