name: Best-Movies | Next.js 13 CI/CD

on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo values"
        run: |
          echo ${{secrets.VERCEL_TOKEN }}
          echo  ${{secrets.VERCEL_TOKEN }}
